name: ui_tests_units
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^4.3.3
  google_fonts: ^1.1.1
  cached_network_image: ^2.5.0
  flutter_svg: ^0.19.1
  dots_indicator: ^1.2.0
  get_it: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/svg/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
